export type LocationSeed = {
  slug: string;
  name: string;
  kind: 'country' | 'region' | 'city';
  lat: string;
  lng: string;
  searchTerms: string[];
};

export const LOCATION_SEEDS: LocationSeed[] = [
  {
    slug: 'chile',
    name: 'Chile',
    kind: 'country',
    lat: '-35.6751',
    lng: '-71.5430',
    searchTerms: [
      'Chile',
      '🇨🇱',
      'CL',
      'CHL',
      'Chile 🇨🇱',
      '🇨🇱 Chile',
      'Chilean',
      'Chile, South America',
      'Chile, Sudamérica',
    ],
  },
  {
    slug: 'arica-y-parinacota',
    name: 'Arica y Parinacota',
    kind: 'region',
    lat: '-18.4783',
    lng: '-70.3126',
    searchTerms: [
      'Arica y Parinacota',
      'Arica y Parinacota, Chile',
      'Región de Arica y Parinacota',
    ],
  },
  {
    slug: 'arica',
    name: 'Arica',
    kind: 'city',
    lat: '-18.4783',
    lng: '-70.3126',
    searchTerms: ['Arica'],
  },
  {
    slug: 'tarapaca',
    name: 'Tarapacá',
    kind: 'region',
    lat: '-20.2307',
    lng: '-70.1357',
    searchTerms: [
      'Tarapacá',
      'Tarapaca',
      'Tarapacá, Chile',
      'Región de Tarapacá',
    ],
  },
  {
    slug: 'iquique',
    name: 'Iquique',
    kind: 'city',
    lat: '-20.2307',
    lng: '-70.1357',
    searchTerms: ['Iquique', 'Iquique, Chile', 'Iquique Chile'],
  },
  {
    slug: 'antofagasta-region',
    name: 'Antofagasta',
    kind: 'region',
    lat: '-23.6509',
    lng: '-70.3975',
    searchTerms: [
      'Región de Antofagasta',
      'Antofagasta Region',
      'Antofagasta, Chile',
    ],
  },
  {
    slug: 'antofagasta',
    name: 'Antofagasta',
    kind: 'city',
    lat: '-23.6509',
    lng: '-70.3975',
    searchTerms: ['Antofagasta', 'Antofagasta, Chile', 'Antofagasta Chile'],
  },
  {
    slug: 'calama',
    name: 'Calama',
    kind: 'city',
    lat: '-22.4667',
    lng: '-68.9333',
    searchTerms: ['Calama', 'Calama, Chile', 'Calama Chile'],
  },
  {
    slug: 'atacama',
    name: 'Atacama',
    kind: 'region',
    lat: '-27.3668',
    lng: '-70.3323',
    searchTerms: ['Atacama', 'Atacama, Chile', 'Región de Atacama'],
  },
  {
    slug: 'copiapo',
    name: 'Copiapó',
    kind: 'city',
    lat: '-27.3668',
    lng: '-70.3323',
    searchTerms: ['Copiapó', 'Copiapo', 'Copiapó, Chile', 'Copiapo, Chile'],
  },
  {
    slug: 'coquimbo-region',
    name: 'Coquimbo',
    kind: 'region',
    lat: '-29.9533',
    lng: '-71.3436',
    searchTerms: ['Región de Coquimbo', 'Coquimbo Region', 'Coquimbo, Chile'],
  },
  {
    slug: 'la-serena',
    name: 'La Serena',
    kind: 'city',
    lat: '-29.9027',
    lng: '-71.2519',
    searchTerms: ['La Serena', 'La Serena, Chile', 'La Serena Chile', 'Ovalle'],
  },
  {
    slug: 'coquimbo',
    name: 'Coquimbo',
    kind: 'city',
    lat: '-29.9533',
    lng: '-71.3436',
    searchTerms: ['Coquimbo', 'Coquimbo, Chile', 'Coquimbo Chile'],
  },
  {
    slug: 'valparaiso-region',
    name: 'Valparaíso',
    kind: 'region',
    lat: '-33.0472',
    lng: '-71.6127',
    searchTerms: [
      'Región de Valparaíso',
      'Valparaiso Region',
      'Valparaíso, Chile',
      'Valparaiso, Chile',
    ],
  },
  {
    slug: 'valparaiso',
    name: 'Valparaíso',
    kind: 'city',
    lat: '-33.0472',
    lng: '-71.6127',
    searchTerms: [
      'Valparaíso',
      'Valparaiso',
      'Valparaíso, Chile',
      'Valparaiso, Chile',
      'Valpo',
      // Greater Valparaíso conurbation + nearby towns.
      'Quilpué',
      'Quilpue, Chile',
      'Villa Alemana',
      'Quillota',
      'San Antonio, Chile',
      'Los Andes, Chile',
      'San Felipe, Chile',
      // Universities in the region.
      'Pontificia Universidad Católica de Valparaíso',
      'Universidad Técnica Federico Santa María',
      'Universidad de Valparaíso',
    ],
  },
  {
    slug: 'vina-del-mar',
    name: 'Viña del Mar',
    kind: 'city',
    lat: '-33.0153',
    lng: '-71.5500',
    searchTerms: [
      'Viña del Mar',
      'Vina del Mar',
      'Viña del Mar, Chile',
      'Vina del Mar, Chile',
    ],
  },
  {
    slug: 'metropolitana',
    name: 'Región Metropolitana',
    kind: 'region',
    lat: '-33.4489',
    lng: '-70.6693',
    searchTerms: [
      'Región Metropolitana',
      'Region Metropolitana',
      'Metropolitana de Santiago',
      'Región Metropolitana de Santiago',
      'RM, Chile',
    ],
  },
  {
    slug: 'santiago',
    name: 'Santiago',
    kind: 'city',
    lat: '-33.4489',
    lng: '-70.6693',
    searchTerms: [
      'Santiago',
      'Santiago, Chile',
      'Santiago Chile',
      'Stgo',
      'Stgo, Chile',
      'Santiago de Chile',
      'Gran Santiago',
      'Greater Santiago',
      // Greater Santiago comunas. Distinctive ones are queried bare; more
      // ambiguous ones are scoped with ", Chile" to limit foreign false matches.
      'Ñuñoa',
      'Nunoa',
      'Las Condes',
      'Vitacura',
      'Providencia, Chile',
      'Maipú',
      'Maipu, Chile',
      'Puente Alto',
      'La Florida, Chile',
      'Lo Barnechea',
      'Peñalolén',
      'Penalolen',
      'Quilicura',
      'Macul',
      'La Reina, Chile',
      'San Bernardo, Chile',
      'Recoleta, Chile',
      'Independencia, Chile',
      'San Miguel, Chile',
      'Estación Central',
      'La Pintana',
      // Santiago universities that people sometimes set as their location.
      'Universidad de Chile',
      'Pontificia Universidad Católica de Chile',
      'Universidad de Santiago de Chile',
    ],
  },
  {
    slug: 'ohiggins',
    name: "O'Higgins",
    kind: 'region',
    lat: '-34.1708',
    lng: '-70.7444',
    searchTerms: [
      "O'Higgins",
      'OHiggins',
      "Libertador General Bernardo O'Higgins",
      "Región de O'Higgins",
      "O'Higgins, Chile",
    ],
  },
  {
    slug: 'rancagua',
    name: 'Rancagua',
    kind: 'city',
    lat: '-34.1708',
    lng: '-70.7444',
    searchTerms: ['Rancagua', 'Rancagua, Chile', 'Rancagua Chile'],
  },
  {
    slug: 'maule',
    name: 'Maule',
    kind: 'region',
    lat: '-35.4264',
    lng: '-71.6554',
    searchTerms: ['Maule', 'Maule, Chile', 'Región del Maule'],
  },
  {
    slug: 'talca',
    name: 'Talca',
    kind: 'city',
    lat: '-35.4264',
    lng: '-71.6554',
    searchTerms: [
      'Talca',
      'Talca, Chile',
      'Talca Chile',
      'Curicó',
      'Curico, Chile',
      'Linares, Chile',
    ],
  },
  {
    slug: 'nuble',
    name: 'Ñuble',
    kind: 'region',
    lat: '-36.6067',
    lng: '-72.1034',
    searchTerms: ['Ñuble', 'Nuble', 'Ñuble, Chile', 'Región de Ñuble'],
  },
  {
    slug: 'chillan',
    name: 'Chillán',
    kind: 'city',
    lat: '-36.6067',
    lng: '-72.1034',
    searchTerms: ['Chillán', 'Chillan', 'Chillán, Chile', 'Chillan, Chile'],
  },
  {
    slug: 'biobio',
    name: 'Biobío',
    kind: 'region',
    lat: '-36.8270',
    lng: '-73.0503',
    searchTerms: [
      'Biobío',
      'Bio Bio',
      'Bío-Bío',
      'Biobío, Chile',
      'Bío-Bío, Chile',
      'Región del Biobío',
    ],
  },
  {
    slug: 'concepcion',
    name: 'Concepción',
    kind: 'city',
    lat: '-36.8270',
    lng: '-73.0503',
    searchTerms: [
      'Concepción',
      'Concepcion',
      'Concepción, Chile',
      'Concepcion, Chile',
      'Conce',
      'Talcahuano',
      'Universidad de Concepción',
      'Universidad del Bío-Bío',
    ],
  },
  {
    // DO NOT include "Los Angeles" because
    // it's a city in California, USA.
    // and we don't want to confuse it with "Los Ángeles", Chile.
    slug: 'los-angeles',
    name: 'Los Ángeles',
    kind: 'city',
    lat: '-37.4669',
    lng: '-72.3537',
    searchTerms: [
      'Los Ángeles',
      'Los Ángeles, Chile',
      'Los Angeles, Chile',
      'Los Ángeles Chile',
      'Los Angeles Chile',
    ],
  },
  {
    slug: 'araucania',
    name: 'La Araucanía',
    kind: 'region',
    lat: '-38.7359',
    lng: '-72.5904',
    searchTerms: [
      'La Araucanía',
      'Araucania',
      'La Araucanía, Chile',
      'Región de la Araucanía',
    ],
  },
  {
    slug: 'temuco',
    name: 'Temuco',
    kind: 'city',
    lat: '-38.7359',
    lng: '-72.5904',
    searchTerms: [
      'Temuco',
      'Temuco, Chile',
      'Temuco Chile',
      'Angol',
      'Padre Las Casas, Chile',
    ],
  },
  {
    slug: 'los-rios',
    name: 'Los Ríos',
    kind: 'region',
    lat: '-39.8142',
    lng: '-73.2459',
    searchTerms: [
      'Los Ríos',
      'Los Rios',
      'Los Ríos, Chile',
      'Región de Los Ríos',
    ],
  },
  {
    slug: 'valdivia',
    name: 'Valdivia',
    kind: 'city',
    lat: '-39.8142',
    lng: '-73.2459',
    searchTerms: ['Valdivia', 'Valdivia, Chile', 'Valdivia Chile'],
  },
  {
    slug: 'los-lagos',
    name: 'Los Lagos',
    kind: 'region',
    lat: '-41.4693',
    lng: '-72.9424',
    searchTerms: ['Los Lagos', 'Los Lagos, Chile', 'Región de Los Lagos'],
  },
  {
    slug: 'puerto-montt',
    name: 'Puerto Montt',
    kind: 'city',
    lat: '-41.4693',
    lng: '-72.9424',
    searchTerms: [
      'Puerto Montt',
      'Puerto Montt, Chile',
      'Puerto Montt Chile',
      'Puerto Varas',
      'Castro, Chiloé',
      'Chiloé',
    ],
  },
  {
    slug: 'osorno',
    name: 'Osorno',
    kind: 'city',
    lat: '-40.5730',
    lng: '-73.1350',
    searchTerms: ['Osorno', 'Osorno, Chile', 'Osorno Chile'],
  },
  {
    slug: 'aysen',
    name: 'Aysén',
    kind: 'region',
    lat: '-45.5752',
    lng: '-72.0662',
    searchTerms: [
      'Aysén',
      'Aysen',
      'Aysén, Chile',
      'Región de Aysén',
      'Región Aysén del General Carlos Ibáñez del Campo',
    ],
  },
  {
    slug: 'coyhaique',
    name: 'Coyhaique',
    kind: 'city',
    lat: '-45.5752',
    lng: '-72.0662',
    searchTerms: ['Coyhaique', 'Coyhaique, Chile', 'Coyhaique Chile'],
  },
  {
    slug: 'magallanes',
    name: 'Magallanes',
    kind: 'region',
    lat: '-53.1638',
    lng: '-70.9171',
    searchTerms: [
      'Magallanes',
      'Magallanes, Chile',
      'Región de Magallanes',
      'Región de Magallanes y de la Antártica Chilena',
    ],
  },
  {
    slug: 'punta-arenas',
    name: 'Punta Arenas',
    kind: 'city',
    lat: '-53.1638',
    lng: '-70.9171',
    searchTerms: ['Punta Arenas', 'Punta Arenas, Chile', 'Punta Arenas Chile'],
  },
];
