function normalizeQualifier(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

const LATIN_AMERICA = [
  'Argentina',
  'Bolivia',
  'Brasil',
  'Brazil',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Dominican Republic',
  'Ecuador',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Mexico',
  'México',
  'Nicaragua',
  'Panama',
  'Panamá',
  'Paraguay',
  'Peru',
  'Perú',
  'Puerto Rico',
  'Uruguay',
  'Venezuela',
];

const NORTH_AMERICA = [
  'Canada',
  'Canadá',
  'United States',
  'United States of America',
  'USA',
  'US',
  'U.S.',
  'U.S.A.',
  'EEUU',
  'Estados Unidos',
];

const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'District of Columbia',
  'Washington DC',
  'Washington D.C.',
];

const US_STATE_CODES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
  'DC',
];

const CANADIAN_PROVINCES = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Québec',
  'Saskatchewan',
  'Northwest Territories',
  'Nunavut',
  'Yukon',
];

const CANADIAN_PROVINCE_CODES = [
  'AB',
  'BC',
  'MB',
  'NB',
  'NL',
  'NS',
  'NT',
  'NU',
  'ON',
  'PE',
  'QC',
  'SK',
  'YT',
];

const WESTERN_EUROPE = [
  'Austria',
  'Österreich',
  'Belgium',
  'België',
  'Belgie',
  'France',
  'Germany',
  'Deutschland',
  'Ireland',
  'Éire',
  'Italy',
  'Italia',
  'Luxembourg',
  'Netherlands',
  'Holland',
  'Nederland',
  'Portugal',
  'Spain',
  'España',
  'Espana',
  'Switzerland',
  'Schweiz',
  'Suisse',
  'United Kingdom',
  'UK',
  'Great Britain',
  'England',
  'Scotland',
  'Wales',
  'Northern Ireland',
];

const SPANISH_REGIONS = [
  'Andalucía',
  'Andalucia',
  'Andalusia',
  'Aragón',
  'Aragon',
  'Asturias',
  'Balearic Islands',
  'Islas Baleares',
  'Basque Country',
  'País Vasco',
  'Pais Vasco',
  'Canary Islands',
  'Islas Canarias',
  'Cantabria',
  'Castilla-La Mancha',
  'Castilla y León',
  'Castilla y Leon',
  'Catalonia',
  'Cataluña',
  'Catalunya',
  'Extremadura',
  'Galicia',
  'La Rioja',
  'Madrid',
  'Murcia',
  'Navarra',
  'Valencia',
  'Comunidad Valenciana',
  'Compostela',
  'Barcelona',
  'Sevilla',
  'Seville',
  'Málaga',
  'Malaga',
  'Bilbao',
  'Zaragoza',
];

const NORTHERN_EASTERN_EUROPE = [
  'Albania',
  'Belarus',
  'Bosnia',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'Greece',
  'Hungary',
  'Iceland',
  'Latvia',
  'Lithuania',
  'Montenegro',
  'North Macedonia',
  'Macedonia',
  'Norway',
  'Poland',
  'Romania',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Sweden',
  'Ukraine',
  'Russia',
  'Russian Federation',
];

const ASIA_PACIFIC = [
  'Afghanistan',
  'Australia',
  'Bangladesh',
  'Cambodia',
  'China',
  'Hong Kong',
  'India',
  'Indonesia',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'South Korea',
  'Korea',
  'Republic of Korea',
  'North Korea',
  'Kuwait',
  'Lebanon',
  'Malaysia',
  'Myanmar',
  'Nepal',
  'New Zealand',
  'Pakistan',
  'Philippines',
  'Qatar',
  'Saudi Arabia',
  'Singapore',
  'Sri Lanka',
  'Taiwan',
  'Thailand',
  'Turkey',
  'Türkiye',
  'Turkiye',
  'United Arab Emirates',
  'UAE',
  'Vietnam',
  'Việt Nam',
];

const AFRICA_MIDDLE_EAST = [
  'Algeria',
  'Angola',
  'Cameroon',
  'Egypt',
  'Ethiopia',
  'Ghana',
  'Iran',
  'Iraq',
  'Kenya',
  'Morocco',
  'Mozambique',
  'Nigeria',
  'Senegal',
  'South Africa',
  'Sudan',
  'Tanzania',
  'Tunisia',
  'Uganda',
  'Zimbabwe',
];

const COLLIDING_FOREIGN_PLACES = [
  'Santiago de Compostela',
  'Santiago de Cuba',
  'Buenos Aires',
  'São Paulo',
  'Sao Paulo',
  'Rio de Janeiro',
  'Mexico City',
  'Ciudad de México',
  'Ciudad de Mexico',
  'Bogotá',
  'Bogota',
  'Lima',
  'Montevideo',
  'Caracas',
  'Quito',
  'La Paz',
  'Asunción',
  'Asuncion',
  'San José',
  'San Jose',
  'San Salvador',
  'San Francisco',
  'San Diego',
  'San Antonio',
  'San Juan',
];

const RAW_FOREIGN_QUALIFIERS = [
  ...LATIN_AMERICA,
  ...NORTH_AMERICA,
  ...US_STATES,
  ...US_STATE_CODES,
  ...CANADIAN_PROVINCES,
  ...CANADIAN_PROVINCE_CODES,
  ...WESTERN_EUROPE,
  ...SPANISH_REGIONS,
  ...NORTHERN_EASTERN_EUROPE,
  ...ASIA_PACIFIC,
  ...AFRICA_MIDDLE_EAST,
  ...COLLIDING_FOREIGN_PLACES,
];

export const FOREIGN_QUALIFIERS = new Set(
  RAW_FOREIGN_QUALIFIERS.flatMap((qualifier) => {
    const normalized = normalizeQualifier(qualifier);
    const parts = normalized.split(/[,/|·]/).map((part) => part.trim());
    return [normalized, ...parts.filter(Boolean)];
  }),
);
